import SideBar from "../../components/SideBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { SessionProvider } from "../../components/SessionProvider";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import Login from "../../components/Login";
import ClientProvider from "../../components/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ChatGPT Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-scroll md:min-w-[20rem]">
                <SideBar />
              </div>
              <ClientProvider />

              <div className="bg-[#343541] flex-1">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
